### ISSUE TITLE
Stuttering SPI

### ISSUE THREAD

**Issue by eekcage** [macpod/lasershark_firmware#1]
Hello,

Thanks for all the work you have put into this project. About a year and a half ago I made my lasershark and had it working well in all pps. Now I have gone back to the project I find Stuttering in any rate but 64k pps. I've tried every FW revision and have compiled it myself too making a few changes that I thought would help.

I'm not certain it's the lasershark (I have no LPC debug capability at the moment) but the SPI clock is showing 4 packets as normal in 64k pps and no stuttering. then in 32k pps the clock shows 4 packets then a burst of ~40*2pkt then back to 4pkt.

This was using lasershark_jack, but it happens on stdin too. I hope this is detailed enough. Attached a picture below to aid my useless explaination

[Image](https://www.dropbox.com/s/o61bcva74cyy6eq/DS1Z_QuickPrint2.png?dl=0)

Edit: The stuttering is creating bright spots of laser at what appears to be random intervals on the display. And i've just noticed the number of 2pkt burst changes from anywhere between 2 to 120.

**Comment by eekcage** [comment]
I could be an idiot. Just been playing around and I now realise that during the 2pkt bursts the output is blanked. It wasn't like this ~a year ago. I wonder what changed?

**Comment by macpod** [comment]
Sounds like you figured it out before I even had a chance to read this. Glad you got it worked out!
